export const FETCH_PORTFOLIO_LIST_REQUEST = "FETCH_PORTFOLIO_LIST_REQUEST";
export const FETCH_PORTFOLIO_LIST_SUCCESS = "FETCH_PORTFOLIO_LIST_SUCCESS";
export const FETCH_PORTFOLIO_LIST_FAILURE = "FETCH_PORTFOLIO_LIST_FAILURE";
export const FETCH_PORTFOLIO_REQUEST = "FETCH_PORTFOLIO_REQUEST";
export const FETCH_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const FETCH_PORTFOLIO_FAILURE = "FETCH_PORTFOLIO_FAILURE";
