export const FETCH_COMPANY_LIST_REQUEST = "FETCH_COMPANY_LIST_REQUEST";
export const FETCH_COMPANY_LIST_SUCCESS = "FETCH_COMPANY_LIST_SUCCESS";
export const FETCH_COMPANY_LIST_FAILURE = "FETCH_COMPANY_LIST_FAILURE";
